# Node.js with React - Build and Test Pipeline

trigger:
  branches:
    include:
      - main  # Replace 'main' with your main branch name
  paths:
    exclude:
      - README.md  # Exclude files or directories from triggering pipeline on changes

pool:
  vmImage: ubuntu-latest

jobs:
- job: Build
  displayName: 'Build Job'
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '14.x'  # Define Node.js version
    displayName: 'Install Node.js'

  - script: |
      npm install
      npm run build
    displayName: 'Build'

- job: RunTests
  displayName: 'Run Tests'
  dependsOn: Build  # Ensure tests run after successful build
  steps:
  - script: |
      npm install
      npm test
    displayName: 'Run unit tests'
